[package]
name = "gojira"
version = "0.1.0"
authors = ["Jason Campbell <jasoncampbell@google.com>"]
license = "ISC"

[dependencies]
clap = "2.26.2"
error-chain = "0.11.0"
hyper = "0.11.6"
futures = "0.1"
tokio-core = "0.1"
serde_json = "1.0.3"
hyper-tls = "0.1.2"
native-tls = "0.1"
